// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211005220209_AutoIncrementalId")]
    partial class AutoIncrementalId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("API.Entities.EmailInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SLA")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("API.Entities.SLA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServicesLA");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Internal"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Multilevel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
